kind: pipeline
name: build

steps:
  - name: build_base_alpine
    image: docker
    privileged: true
    volumes:
#      - name: maven
#        path: /root/.m2
#      - name: docker
#        path: /bin/docker
      - name: sock
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker/config.json
    commands:
      - sed -i "s/dl-cdn.alpinelinux.org/mirrors.nju.edu.cn/g" /etc/apk/repositories
      - apk add docker
      - dnf -y install  java-11-openjdk-devel
      - dnf -y install  maven
      - dnf -y install  curl
      - chmod -R 777 /bin
      - which docker
      - docker version
      - source /etc/profile
      - mvn clean compile exec:java -Dexec.mainClass="com.k.docker.jenkins.JenkinsBuildShell" -Dexec.args="ws=/drone/src@thread=1@rep=false@push=true@in=alpine:docker"
      - pwd;ls
      - chmod -R 777 .
      - cd ./target
      - sh ./aliyun_beijing_true.sh
volumes:
#  - name: maven
#    host:
#      path: /opt/soft/docker/data/maven/m2
#  - name: docker
#    host:
#      path: /usr/bin/docker
  - name: sock
    host:
      path: /var/run/docker.sock
  - name: docker_config
    host:
      path: /opt/soft/docker/data/jenkins/jkwk/config.json