kind: pipeline
name: build

steps:
  - name: build
    image: registry.cn-beijing.aliyuncs.com/king019/alpine:docker
    privileged: true
    volumes:
      - name: maven
        path: /root/.m2
      - name: sock
        path: /var/run/docker.sock
    commands:
      - chmod -R 777 /bin
      - which docker
      - docker version
      - source /etc/profile
      - mvn clean compile exec:java -Dexec.mainClass="com.k.docker.jenkins.JenkinsBuildShell" -Dexec.args="ws=/drone/src@thread=1@rep=true@push=false@local=true@ex=centos"
      - pwd;ls
      - sh ./target/local_region/platform/noSuffix_false.sh
volumes:
  - name: maven
    host:
      path: /opt/soft/docker/data/maven/m2
  - name: sock
    host:
      path: /var/run/docker.sock