kind: pipeline
name: compile

steps:
  - name: compile
    image: king019/alpine
    privileged: true
    volumes:
      - name: maven
        path: /root/.m2
      - name: docker
        path: /bin/docker
    commands:
      - chmod -R 777 /bin
      - which docker
      - mvn clean
      - mvn compile exec:java -Dexec.mainClass="com.k.docker.jenkins.JenkinsBuildShell" -Dexec.args="ws=/drone/src@thread=1@rep=true@push=true"
      - pwd;ls
      - sh ./target/local_region/noSuffix_false.sh
volumes:
  - name: maven
    host:
      path: /opt/soft/docker/data/maven/m2
  - name: docker
    host:
      path: /usr/bin/docker