language: java
jdk:
  - openjdk11
services:
  - docker  #需要的docker环境
install:
  - mvn compile exec:java -Dexec.mainClass="com.k.docker.jenkins.JenkinsBuildShell" -Dexec.args="ws=/home/travis/build/king019/docker@thread=1@rep=false@push=true"
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - pwd;ls
  - sh ./target/x86_64_docker_true.sh  # push