        #docker run -it -e DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }} -e DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} -e ALIYUN_USERNAME=$ALIYUN_USERNAME -e ALIYUN_PASSWORD=$ALIYUN_PASSWORD --privileged -v /var/run/docker.sock:/var/run/docker.sock king019/docker:builddocker

name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build
         uses: docker/setup-buildx-action@v1
      - name: act
        run: echo 123
