name: dk
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: docker
        uses: king019/docker@master
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build
      - run: npm test